### ISSUE TITLE
Auth to Azure AD is failing; Can't find module file; 

### ISSUE THREAD

**Issue by jeffl86** [markstan/Test-IntuneFirewallRules#7]
Can't find file in Azure AD module.  Seems module may be deprecated?

https://learn.microsoft.com/en-us/entra/identity-platform/msal-migration

__Checking for AzureAD module...
Get-AuthToken : Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly
'file:///C:\Program
Files\WindowsPowerShell\Modules\AzureAD\2.0.2.182\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' or one of its
dependencies. The system cannot find the file specified."
At C:\temp\Test-IntuneFirewallRules.ps1:1625 char:23_

**Comment by markstan** [comment]
Thanks for the heads-up, @jeffl86. I've checked in a fix that removes the AzureAD module dependency (deprecated on 3/30/2024).

**Comment by jeffl86** [comment]
Thanks Mark!  I did have to run this command to get it to work in my environment.  
Connect-MgGraph -Scopes DeviceManagementConfiguration.Read.All
